name: Static Code Analysis

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up PHP
        uses: shivammathur/setup-php@47129765c5f7986685a6b8d88bbea4a132acf7da # 2.35.0
        with:
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Run psalm
        run: composer psalm -- --output-format=github
